language: scala

jdk: openjdk8

scala:
  - 2.11.12

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - sudo apt-get -y install perl
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

services:
  - postgresql


before_script:
  - cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm Mojolicious
  - cpanm JSON::Parse
  - perl src/test/resources/script/mock_api.pl daemon -m dev -l http://\*:3000 &

after_script:
  - killall -9 perl

script:
  - sbt +test



